### ISSUE TITLE
Class Editor lacks capability to define textual field value on image

### ISSUE THREAD

**Issue by vkotkas** [ambjsdp/CoCoViLa#10]
The following construction is used to define a textual element in a class image that presents a value of a given field:
![snapshot1](https://cloud.githubusercontent.com/assets/7438021/5630414/53fc528e-95c6-11e4-8f27-bcf6e4944424.png)

**Comment by AnnaMol** [comment]
Class fields functionality is done. In case there will be bugs connected to class fields, it will be easier to fix, if each bug has separate description
