### ISSUE TITLE
Class Editor does not load undefined ports

### ISSUE THREAD

**Issue by vkotkas** [ambjsdp/CoCoViLa#15]
When a port is not defined in the specification it's graphics is not loaded.

Parsing pops up a warning that "corresponding field must be defined", which is not the case.

Class Editor allows to save pictures without corresponding variables defined in the specification.

Proper behavior would be:
When class image is saved the specification is checked to ensure all variables are properly defined. When any of them is missing a proper warning should pop up.
When class is loaded into Class Editor that has a missing variable in the specification a warning should pop up (once) but the graphics should still be loaded.

**Comment by AnnaMol** [comment]
Could not reproduce
