### ISSUE TITLE
Class Editor has no interface to a bitmap editor for composing icons

### ISSUE THREAD

**Issue by vkotkas** [ambjsdp/CoCoViLa#16]

**Comment by ambjsdp** [comment]
I remember agreeing that we will not implement this

**Comment by vkotkas** [comment]
I remember we agreed that it is of the least priority, Without it the Class Editor is inconvinient to use.

**Comment by vkotkas** [comment]
It is agreed that there should be a preview for selecting an icon and no interface to an editor is to be made.
