### ISSUE TITLE
 Class Editor does not allow proper selection and modification of horisontal or vertical lines. Continuation of #4

### ISSUE THREAD

**Issue by vkotkas** [ambjsdp/CoCoViLa#24]

**Comment by vkotkas** [comment]
This is holding also incase of other shapes when thay became too narrow.
Probably the area where an object responds to a mouse clicks should be slightly larger than the shape itself e.g. the size of bounding markers

**Comment by AnnaMol** [comment]
I have increased catchment areaby 3 points for ALL shapes  for consistency reasons. If you think this should only apply to narrow shapes i can make changes
