### ISSUE TITLE
Arc drawing results in negative Arc Angle

### ISSUE THREAD

**Issue by vkotkas** [ambjsdp/CoCoViLa#26]
Start with drawing an arc.
Draw the surrounding rectangle and start the arc from the bottom-right corner of the surrounding rectangle. Somewhere somewhere at the bottom-center the arc angle flips to negative, probably where the x-coordinate equals to the x coordinate of the center of the arc.

**Comment by areitsakas** [comment]
It was effect of defining arc angle as positive only parameter. Actually angle must be negative for clockwise arcs.
