### ISSUE TITLE
Erazer tool behaves strangely

### ISSUE THREAD

**Issue by vkotkas** [ambjsdp/CoCoViLa#36]
It is unclear which object will be erased when the tool is used.

**Comment by AnnaMol** [comment]
Eraser tool atm deletes selected object and clicked object
Should it delete selected object?

**Comment by AnnaMol** [comment]
Expected Eraser functionality
a) if some shape is selected
click inside selected shape - delete it
click outside selected shape - do nothing
b) no selected shapes
click inside shape - delete it
click inside multiple shapes - delete top by order
