### ISSUE TITLE
Editor falls back to selection mode after adding an arc shape

### ISSUE THREAD

**Issue by vkotkas** [ambjsdp/CoCoViLa#47]
In case of all other shapes the editor remains in the same mode (adding lines or rectangles etc).
When adding an arc - the operation should be cancelled when surrounding rectangle with 0 height/width is drawn. Currently, after a single click user needs to make another click to be released from the adding arc workflow.

**Comment by AnnaMol** [comment]
On our meeting 6.04 we have agreed that's expected behavior, and all other shapes should also switch to selection mode. So which behavior should it be for all shapes? Stay or switch to selection?

**Comment by vkotkas** [comment]
We agreed that the behaviour should be uniform. Currently in some cases it falls back and in most cases it does not. I proposed (different to that previous agreement) to to enable right-mouse-click to open area that will fall back to editing mode. Both solutions are ok, but I believe that the new proposal is more convenient.
