### ISSUE TITLE
Right mouse click functionality

### ISSUE THREAD

**Issue by AnnaMol** [ambjsdp/CoCoViLa#56]
1) Click on empty space
Clear all selected;
Set state Selection
2) Click on shape (or multiple shapes)
Select shape (top one by order if >1);
Pop up shape Menu;
State stays the same
i.e state DrawRect, right click new Rect
new Rect is selected, shape MenuPopUp for new Rect
state stays DrawRect

Correct?

**Comment by vkotkas** [comment]
Looks all right! And middle-click should do nothing for now (in Scheme Editor middle-click opens java class).
