### ISSUE TITLE
selection markers zooming

### ISSUE THREAD

**Issue by vkotkas** [ambjsdp/CoCoViLa#63]
when zooming in also the selection markers (black rectangles in the shape corners) become larger. This is unexpected.

**Comment by vkotkas** [comment]
selection markers also worn non-uniformly
e.g upper right corner marker of a rectangle start resizing when clicked outside it (below)
line selection markers start one line end moving when clicked outside the corner markers - this is unexpected as clicking on a line outside the markers should move the line.

**Comment by AnnaMol** [comment]
We have agreed that selection marks should zoom
